[package]
name = "SpacesBinarySearchTree"
version = "0.1.0"
edition = "2021"
authors = ["Space_Nerd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
